### PR TITLE
[bugfix] Fixing the cli to not run watch mode when using the push flag

### LINKED ISSUE #62: Push no longer works in v5
The below command is no longer working with v5.

```
./node_modules/.bin/aemsync -p /mnt/nvme1n1p1/patrickh/code/proj/ui.apps/src/main/content/jcr_root/apps/group/proj -t http://admin:admin@localhost:4502
```
It looks like in v5, the `-p` flag and value no longer have any effect when using the CLI.

### PR DESCRIPTION
**Pull request by patrickhousley**
This fixes the CLI so that the cli does not attempt to go into watch mode when the `-p` flag is passed. Additionally, this fixes the push flag value to be properly wrapped as an array. Without that, we are getting the below output from the CLI.

```
Package contents:
  undefined
Response log:
  undefined
```

closes #62

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -277,6 +277,7 @@ export async function main () {
   if (args.payload) {
     for await (const result of push(args)) {
```
Comment (gavoja) [inline index.js:278]: The loop here is unnecessary. Can be replaced with something like this:
```js
const result = (await push(args).next()).value
debugResult(result)
return
```

**Review by gavoja — CHANGES_REQUESTED** [review]
Please bump up the patch version in the `package.json` and remove the for loop when the payload is provided.

Thanks for spotting this!

File: index.js (hunk 1 above)
Comment (patrickhousley) [reply index.js]: Fixed it so the `-p` flag can be provided multiple times.

File: index.js [hunk 2]
```diff
@@ -275,9 +284,9 @@ export async function main () {
   // Path to push does not have to exist.
   // Non-existing path can be used for deletion.
   if (args.payload) {
-    for await (const result of push(args)) {
-      debugResult(result)
-    }
+    const result = push(args)
```
Comment (gavoja) [inline index.js:287]: The `push()` is an asynchronous generator. For the `result` to be returned, it needs to be awaited:
```js
const result = (await push(args).next()).value
```

**Review by gavoja — CHANGES_REQUESTED** [review]

File: index.js (hunk 2 above)
Comment (patrickhousley) [reply index.js]: Yup forgot about that. Fixed

**Review by gavoja — APPROVED** [review]
